### ISSUE TITLE
Suggest Changes

### ISSUE THREAD

**Issue by juharris** [juharris/code-reviewer#33]
It would be helpful to include a suggested fix in comments. We can support a list of fixes to apply in the configuration. For example:
```yaml
- diff_pattern: '\s+$'
  corrections:
    - find: '^(.*?)\s+$'
      replacement: '\1'
```

Need to support deleting the line (including the newline character).

This will be very useful for when we support running on local files as we can use the corrections to support automatically changing files.
