### ISSUE TITLE
Correct Suggestion when diff_pattern doesn't match the full line

### ISSUE THREAD

**Issue by juharris** [juharris/code-reviewer#41]
Issue when using a diff_pattern that doesn't match a full line and then a suggestion because the suggestion includes the full line, but the comment is only on the part that matches diff_pattern.

Repro (probably, not tested exactly)
File contents:
> hello ABCD

```yaml
path_pattern: '.'
diff_pattern: '^.*A'
suggestions:
  - pattern: 'A'
    replacement: 'F'
```

The suggestion should just be: 'hello F'
